imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            # fingers_crossed handler čuva sve poruke tijekom requesta, i sve ih prosljeđuje drugom handleru ali samo ako
            # postoji barem jedna poruka razine "error" ili veća. Na ovaj način osiguravamo da u slučaju ozbiljne greške
            # imamo log cijelog problematičnog requesta.
            action_level: error
            # U ovom slučaju main fingers_crossed handler prosljeđuje poruke nested handleru
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        # Ovaj log handler dobija sve poruke neovisno o main (fingers_crossed) handleru
        not_nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%_sve_poruke.log"
            level: debug
        console:
            type:  console
